insert into `customer` (`id`,`firstName`,`lastName`,`birthDate`) values (1, "Reed", "Edwards", "1952-08-16");
insert into `customer` (`id`,`firstName`,`lastName`,`birthDate`) values (2, "Iliana", "Glenn", "1964-03-12");
insert into `customer` (`id`,`firstName`,`lastName`,`birthDate`) values (3, "Aola", "Canon", "1979-02-04");
insert into `customer` (`id`,`firstName`,`lastName`,`birthDate`) values (4, "Fatima", "Hamilton", "1989-03-29");
insert into `customer` (`id`,`firstName`,`lastName`,`birthDate`) values (5, "Chaney", "Green", "1978-11-19");
insert into `customer` (`id`,`firstName`,`lastName`,`birthDate`) values (6, "Sharon", "Watts", "1988-01-09");
insert into `customer` (`id`,`firstName`,`lastName`,`birthDate`) values (7, "Norman", "Tanner", "1973-09-28");
insert into `customer` (`id`,`firstName`,`lastName`,`birthDate`) values (8, "Olga", "Mays", "1969-05-03");
insert into `customer` (`id`,`firstName`,`lastName`,`birthDate`) values (9, "Kennedy", "Hoffman", "1977-10-18");
insert into `customer` (`id`,`firstName`,`lastName`,`birthDate`) values (10, "Avangeline", "Horn", "1983-09-23");
commit;